language: node_js
node_js:
- '0.10'
script: make test-ci
install:
- npm install
- npm install bower -g
addons:
  sauce_connect: true
env:
  global:
  - secure: CobqmywLsSteYgnmsjGsNEp7LTa2Y4Fjoa0qvwAbyz2WueM1i5OXSSEaBQuWLPlrNn9hLh8vhBli//aanu45LGak3SPAHyvo9UCXd5gY8adykYFtrHWmKf0bKf8a8cHtrf8QjaUiG1OIezl2Pf2u+zMyY/wvOrgfiGnGqXwSUJc=
  - secure: YQifxQx61jTeLitt3NTwOwprf5HTPnnbW4Ou+uAznUogKtVXIYcV8h+jKH+uqNSwiU0S4KwUnPVgbauA7G1UVYLYUGcqMHsjIqoRB6mC/lP4BcgKK9RbPCyYPTb+/pBQM97mbvQ6r8I87LvZeK2tLBZ5mnxwBo/R6tpiDDt5R24=
