language: node_js
sudo: required
dist: xenial
node_js:
  - 8
  - 10
  - 12
  - node
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
services:
  - xvfb
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
before_script:
- npm install
script:
- npm test
